import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main_layout">
          <div tabIndex="-1" className="main_container">
            <Header />
            <section className="">
              <div className="min-h-full w-full">{children}</div>
            </section>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
